### ISSUE TITLE
don't work add guard

### ISSUE THREAD

**Issue by m4tronin** [TradeOnSolutions/Steam-Desktop-Authenticator#11]
![Screenshot_7](https://github.com/TradeOnSolutions/Steam-Desktop-Authenticator/assets/79796403/81dfe744-b91d-4b6e-8500-06fff86fd3a6)

**Comment by aleckmal90** [comment]
Hi. It might be steam lags, we are looking into it now. Maybe steam changed something in the process of adding guard and now this function doesn't work, in this case we will fix the code

**Comment by aleckmal90** [comment]
fixed, this is steam lags
