### ISSUE TITLE
All accounts removed after closing

### ISSUE THREAD

**Issue by DaffyExtra** [TradeOnSolutions/Steam-Desktop-Authenticator#2]
I added accounts and then restart the program but it had removed account I ran as admin and added again butt after restart it again removed.

**Comment by aleckmal90** [comment]
Hello, it's on version 1.2?

**Comment by DaffyExtra** [comment]
> Hello, it's on version 1.2?

I have this one
TradeOn.SDA.v_1_1.zip

**Comment by aleckmal90** [comment]
Please, try a new version, 1.2. This version is now available on releases page

**Comment by DaffyExtra** [comment]
okay sure
