### ISSUE TITLE
Error login in steam

### ISSUE THREAD

**Issue by 3ACEPATOP** [TradeOnSolutions/Steam-Desktop-Authenticator#4]
![Снимок экрана 2023-06-28 141217](https://github.com/TradeOnSolutions/Steam-Desktop-Authenticator/assets/137274511/95e0a765-ac81-49b0-92ee-a672a436a3e6)
on almost all my accounts, when I try to log in, I see this. passwords 100% right

**Comment by aleckmal90** [comment]
Hi. We will be releasing version 1.3 soon, there will be a more detailed explanation of the error

**Comment by TradeOnSolutions** [comment]
Updated to the latest version 1.3. Already available
