### ISSUE TITLE
Cannot load confirmations

### ISSUE THREAD

**Issue by 3ACEPATOP** [TradeOnSolutions/Steam-Desktop-Authenticator#8]
![Снимок экрана 2023-06-30 140434](https://github.com/TradeOnSolutions/Steam-Desktop-Authenticator/assets/137274511/9b276e0f-7a8b-45eb-be84-4a6985194ab2)
all day all night)

**Comment by makarworld** [comment]
try re-login

**Comment by aleckmal90** [comment]
Re-Login helps?
